version: '3.1'

services:
  postgres:
    image: postgres:16.0
    container_name: spring-batch-postgres
    environment:
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: